export { default as CreateCategory } from './createCategory.jsx'
export { default as UpdateCategory } from './updateCategory.jsx'
export { default as CreateLocation } from './createLocation.jsx'
export { default as UpdateLocation } from './updateLocation.jsx'
export { default as CreateBanner } from './createBanner.jsx'
export { default as UpdateBanner } from './updateBanner.jsx'